<a href="https://colab.research.google.com/github/ahsal075/ahsal/blob/main/ahsal_numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.

● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np
arr = np.arange(10, 50)
reshaped_arr = arr.reshape(4, 10)
last_column = reshaped_arr[:, -1]
import numpy as np
print("Reshaped 4x10 Matrix:\n", reshaped_arr)
print("\nLast Column:\n", last_column)


Reshaped 4x10 Matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last Column:
 [19 29 39 49]


##2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9

● Add the two matrices

● Multiply them element-wise

● Then find the transpose of the result

In [ ]:
import numpy as np
matrix_5s = np.full((3, 3), 5)
matrix_1to9 = np.arange(1, 10).reshape(3, 3)
added = matrix_5s + matrix_1to9
multiplied = matrix_5s * matrix_1to9
transpose_result = multiplied.T
print("Matrix filled with 5s:\n", matrix_5s)
print("\nMatrix with values 1 to 9:\n", matrix_1to9)
print("\nAdded Matrices:\n", added)
print("\nElement-wise Multiplication:\n", multiplied)
print("\nTranspose of the Multiplication Result:\n", transpose_result)


Matrix filled with 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix with values 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Added Matrices:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplication:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of the Multiplication Result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


##3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1

● Count how many values were replaced.

In [ ]:
import numpy as np
arr = np.random.randint(10, 101, size=15)
print("Original Array:\n", arr)
replaced_arr = arr.copy()
replaced_arr[replaced_arr > 50] = -1
count_replaced = np.sum(arr > 50)
print("\nModified Array:\n", replaced_arr)
print("\nNumber of values replaced:", count_replaced)


Original Array:
 [31 49 31 39 34 43 71 63 66 32 67 66 13 13 60]

Modified Array:
 [31 49 31 39 34 43 -1 -1 -1 32 -1 -1 13 13 -1]

Number of values replaced: 6


##4. Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.

● Normalize each row using the formula:


In [ ]:
import numpy as np
arr = np.random.rand(5, 4)
print("Original Array:\n", arr)
row_sums = np.sum(arr, axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow with Maximum Sum (Index:", max_row_index, "):\n", arr[max_row_index])
normalized_arr = np.zeros_like(arr)
for i in range(arr.shape[0]):
    row = arr[i]
    row_min = np.min(row)
    row_max = np.max(row)
    if row_max != row_min:
        normalized_arr[i] = (row - row_min) / (row_max - row_min)
    else:
        normalized_arr[i] = 0
print("\nNormalized Array:\n", normalized_arr)


Original Array:
 [[0.6799408  0.76635321 0.08983699 0.35186209]
 [0.89439336 0.8360463  0.18928888 0.48494435]
 [0.56856242 0.88777061 0.35966834 0.13333745]
 [0.08255575 0.86547246 0.33348573 0.48641537]
 [0.24491835 0.33937265 0.80484241 0.14140202]]

Row with Maximum Sum (Index: 1 ):
 [0.89439336 0.8360463  0.18928888 0.48494435]

Normalized Array:
 [[0.87226853 1.         0.         0.38731532]
 [1.         0.91725048 0.         0.41930732]
 [0.57689003 1.         0.30000125 0.        ]
 [0.         1.         0.32050661 0.51583983]
 [0.15602958 0.29840003 1.         0.        ]]


##5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements

● Find the duplicates (elements that appear more than once)

In [ ]:
import numpy as np
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)
unique, counts = np.unique(arr, return_counts=True)
duplicates = unique[counts > 1]
print("Duplicate elements:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


##. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.

● Then extract all even numbers from this submatrix.

In [ ]:
import numpy as np
arr = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Array:\n", arr)
submatrix = arr[1:5, 1:5]
print("\nMiddle 4x4 Submatrix:\n", submatrix)
even_numbers = submatrix[submatrix % 2 == 0]
print("\nEven numbers in the 4x4 submatrix:\n", even_numbers)


Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers in the 4x4 submatrix:
 [ 8 10 14 16 20 22 26 28]


##Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)

● Then flatten it into a 1D array

● Convert the 1D array back to shape (4, 3)

In [ ]:
import numpy as np
arr = np.arange(12).reshape(3, 4)
print("Original (3x4) array:\n", arr)
reshaped_2x6 = arr.reshape(2, 6)
print("\nReshaped to (2x6):\n", reshaped_2x6)
flattened = reshaped_2x6.flatten()
print("\nFlattened to 1D:\n", flattened)
reshaped_4x3 = flattened.reshape(4, 3)
print("\nReshaped to (4x3):\n", reshaped_4x3)


Original (3x4) array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]

● Then append a new column [7, 8, 9]

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print("Original array:\n", a)
a = np.vstack([a, [5, 6]])
print("\nAfter appending row [5, 6]:\n", a)
new_col = np.array([[7], [8], [9]])
a = np.hstack([a, new_col])
print("\nAfter appending column [7, 8, 9]:\n", a)


Original array:
 [[1 2]
 [3 4]]

After appending row [5, 6]:
 [[1 2]
 [3 4]
 [5 6]]

After appending column [7, 8, 9]:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


##a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.array([7, 8, 9])

● Join them into a single array

● Reshape the result into a 3×3 matrix

● Extract the diagonal elements

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined = np.concatenate((a, b, c))
print("Joined array:", joined)
matrix_3x3 = joined.reshape(3, 3)
print("\n3x3 matrix:\n", matrix_3x3)
diagonal_elements = np.diag(matrix_3x3)
print("\nDiagonal elements:", diagonal_elements)


Joined array: [1 2 3 4 5 6 7 8 9]

3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]


## Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.

● Count how many such values exist.

In [ ]:
import numpy as np
arr = np.arange(1, 21)
print("Original array:", arr)
divisible_by_3_or_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print("Values divisible by 3 or 5:", divisible_by_3_or_5)
count = divisible_by_3_or_5.size
print("Count:", count)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9
