<a href="https://colab.research.google.com/github/ahsal075/ahsal/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import numpy as np
x = np.array([12,14,156,25,300])
x.shape

(5,)

In [ ]:
import numpy as np
x = np.array([12,14,156,25,300])
x

array([ 12,  14, 156,  25, 300])

In [ ]:
import numpy as np
x = np.array([12,14,156,25,300])
x.size

5

In [ ]:
import numpy as np
x = np.array([12,14,156,25,300])
x.ndim

1

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y.size

12

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y.shape

(3, 4)

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y.ndim

2

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y.dtype

dtype('int64')

##slicing


In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y[0]

array([1, 2, 3, 4])

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y[0][2]

np.int64(3)

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y[1:,2:]

array([[ 8,  9],
       [12, 13]])

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
y[1:,1:3]

array([[ 7,  8],
       [11, 12]])

In [ ]:
import numpy as np
y = np.array([
       [ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]
       ])
np.sum(y)

np.int64(86)

In [ ]:
np.zeros(shape=(3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(3,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(10,20).reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

##datatype


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


##numpy copy vs view

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[4] = 1
print(arr)
print(x)



[1 2 3 4 1]
[1 2 3 4 5]


##numpy array split

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


##numpy arrayfilter

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]
